name = "horticulture-admin"
main = "src/index.js"
compatibility_date = "2026-09-21"
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://shbassinchateaulin.github.io"
GITHUB_OWNER = "shbassinchateaulin"
SITE_REPO = "site-horticulture"
CONTENT_REPO = "horticulture-contenus"
GITHUB_BRANCH = "main"
GOOGLE_APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwim8t9oVshwze47JG0KeuvdiE3hqjwM6pXts9KA48HSd-jLOP5A3V2cyfN6nVMSp5H/exec"

[[d1_databases]]
binding = "DB"
database_name = "horticulture-admin"
database_id = "1bf8009e-9964-4df8-8696-0adec68b2a0d"
